import enum


class RoleName(str, enum.Enum):
    ADMIN = "ADMIN"
    MATERIAL_EXPERT = "MATERIAL_EXPERT"
    CPSE_USER = "CPSE_USER"
    VIEWER = "VIEWER"


class MaterialStatus(str, enum.Enum):
    PENDING = "PENDING"
    PROCESSING = "PROCESSING"
    ANALYZED = "ANALYZED"
    HARMONIZED = "HARMONIZED"
    REJECTED = "REJECTED"
    FAILED = "FAILED"


class Decision(str, enum.Enum):
    AUTO_HARMONIZATION = "AUTO_HARMONIZATION"
    HUMAN_REVIEW_REQUIRED = "HUMAN_REVIEW_REQUIRED"
    LOW_CONFIDENCE = "LOW_CONFIDENCE"
    NO_COMMON_CODE = "NO_COMMON_CODE"


class HarmonizationStatus(str, enum.Enum):
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    AUTO_APPROVED = "AUTO_APPROVED"
    REJECTED = "REJECTED"
    MORE_INFO_REQUESTED = "MORE_INFO_REQUESTED"


class ApprovalStatus(str, enum.Enum):
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    MORE_INFO_REQUESTED = "MORE_INFO_REQUESTED"
    MERGED = "MERGED"
    NOT_SAME_MATERIAL = "NOT_SAME_MATERIAL"


class ApprovalActionType(str, enum.Enum):
    APPROVE = "APPROVE"
    REJECT = "REJECT"
    REQUEST_MORE_INFO = "REQUEST_MORE_INFO"
    MERGE = "MERGE"
    NOT_SAME_MATERIAL = "NOT_SAME_MATERIAL"


class CommonCodeStatus(str, enum.Enum):
    AUTO_GENERATED = "AUTO_GENERATED"
    APPROVED = "APPROVED"
    PENDING = "PENDING"


class ActorType(str, enum.Enum):
    AI_ENGINE = "AI_ENGINE"
    USER = "USER"
    SYSTEM = "SYSTEM"


class UploadStatus(str, enum.Enum):
    VALIDATING = "VALIDATING"
    QUEUED = "QUEUED"
    PROCESSING = "PROCESSING"
    COMPLETED = "COMPLETED"
    PARTIAL = "PARTIAL"
    FAILED = "FAILED"


class NotificationType(str, enum.Enum):
    MATERIAL_UPLOADED = "MATERIAL_UPLOADED"
    AI_ANALYSIS_COMPLETED = "AI_ANALYSIS_COMPLETED"
    HIGH_CONFIDENCE_RECOMMENDATION = "HIGH_CONFIDENCE_RECOMMENDATION"
    HUMAN_APPROVAL_REQUIRED = "HUMAN_APPROVAL_REQUIRED"
    APPROVAL_COMPLETED = "APPROVAL_COMPLETED"
    MATERIAL_REJECTED = "MATERIAL_REJECTED"
    COMMON_CODE_GENERATED = "COMMON_CODE_GENERATED"
    BULK_UPLOAD_COMPLETED = "BULK_UPLOAD_COMPLETED"
    AI_PROCESSING_FAILED = "AI_PROCESSING_FAILED"
